### ISSUE TITLE
fix up the nav bars...

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#1]
... so that kubernetes is the main nav bar which has apps/services/controllers/pods/diagrams as children.

then other nav bars like Images, Logs, Metrics etc...

**Comment by gashcrumb** [comment]
Yep, gonna leave arranging tabs to hawtio-core-perspective and when we create an actual console assembly project.  Will zap that example plugin from hawtio - jmx, and yeah the connect plugin won't work at the moment so we can hide that for now.  Was planning on fixing the sub-tabs to be below the main nav, and would like them to be fixed in place too.
