### ISSUE TITLE
avoid flashing on some pages (pods with pod status and the Apps detail pages are the biggies)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio-kubernetes#12]
we need a more clever caching mechanism so that we only update the UI when things really change; right now we get lots of flashing....

**Comment by davsclaus** [comment]
Yes the apps page is really annoying

**Comment by jstrachan** [comment]
I've tried to fix it - at least we now generally rarely ever update the kube model now unless it really really does change significantly (and not just the resourceVersion changes). But still the flashing is still there...

**Comment by davsclaus** [comment]
The services and pods pages still blink

**Comment by davsclaus** [comment]
Wonder if they need same _hack_ ?

**Comment by gashcrumb** [comment]
I spent awhile investigating it a few weeks back, and the only thing I could really spot is that when they flash off it's because the model doesn't have that value in it for that brief period of time.  My guess is there's a $scope.$apply() at some point when the model is first set on the $scope, then a subsequent $scope.$apply after the model has been updated with these counts, as both calls to $apply() could cause the page to update.  But I couldn't find that pattern in the code at the time, might take another stab now that James got me up and running against os1.fabric8.io :-)

**Comment by davsclaus** [comment]
That sounds like a very good description of what is the real problem.

I think hunting those Core.apply() events can be tricky to resolve.

**Comment by gashcrumb** [comment]
Yay, found it.  The watch that hawtio-simple-table uses basically sees all the changes that are done on the model.  Used an interim array to avoid the frequent page updates, seems to do the trick.

**Comment by jstrachan** [comment]
@gashcrumb who-hoo!!! well played!

**Comment by davsclaus** [comment]
Yat that makes video recoding nicer without those flashing ;)
